### PR TITLE
remove unnecessary JMH dependence

### PR DESCRIPTION
**Pull request by SethTisue**
this eases adding testz to the Scala 2.12 community build.

something about how sbt-jmh operates confuses dbuild; the easiest way to deal with it is is to confine JMH usage to only subprojects which we can exclude from the community build. but "extras" is depended on by "tests", and obviously we would prefer to include "tests".

it appears to me that the line removed here may be vestigial and not needed anyway.

### CODE REVIEW

**Comment by SethTisue** [comment]
see https://github.com/scala/community-builds/pull/830

**Review by dwijnand — APPROVED** [review]

**Review by NeQuissimus — APPROVED** [review]

**Comment by NeQuissimus** [comment]
@hrhino :)

**Comment by SethTisue** [comment]
@hrhino are you (or anyone else) merging PRs in this repo, perchance? it's nbd, but it would also be nice to have it out of my queue

**Comment by hrhino** [comment]
@SethTisue yes; I'll take a look right now. I've been on an OSS moratorium while I get another job's worth of legal issues out of the way, but I'm itching to get back into it.

**Review by hrhino — APPROVED** [review]
After taking a look, that's not worthy of much of a look.

If we ever get benchmarks going, I'll make sure to use a separate project.

**Comment by SethTisue** [comment]
thanks! good luck with the lawyers

**Pull request merged**
